---
title: "Analýza výběru dopravních nehod"
output: html_document
params:
  data_accidents: NA
  period: NA
  accfilter: NA
---

```{r, echo = FALSE}
library(dtplyr, quietly = TRUE)
library(tibble, quietly = TRUE)
library(dplyr, quietly = TRUE)
library(tidyr, quietly = TRUE)
library(lubridate, quietly = TRUE)
library(purrr, quietly = TRUE)
library(stringr, quietly = TRUE)
library(sf, quietly = TRUE)
#library(fs, quietly = TRUE)
#library(readr, quietly = TRUE)
library(ggplot2, quietly = TRUE)
library(tmaptools, quietly = TRUE)
library(tmap, quietly = TRUE)
#library(OpenStreetMap, quietly = TRUE)
library(knitr, quietly = TRUE)
```

```{r, echo=FALSE}
period <- str_c(
  strftime(params$period[1], format = "%d.%m.%Y"),
  " - ",
  strftime(params$period[2], format = "%d.%m.%Y")
)

died <- params$data_accidents |> pull(accident_dead) |> sum(na.rm = TRUE)

swound <- params$data_accidents |> pull(accident_serious_injury) |> sum(na.rm = TRUE)

lwound <- params$data_accidents |> pull(accident_light_injury) |> sum(na.rm = TRUE)


filteraccidents <- c(
    "Bez omezení (zahrnuty jsou všechny nehody)"="all",
    "Pouze nehody s účastí chodce"="pedestrian",
    "Pouze nehody s účastí cyklisty"="bike",
    "Pouze nehody s účastí motocyklisty"="motobike",
    "Pouze nehody, které se staly pod vlivem alkoholu"="alcohol"
  )

accidents <- names(filteraccidents)[filteraccidents == params$accfilter]


format_integer <- function(x){
  x |>
    as.integer() |>
    format(
      nsmall = 0,
      trim = TRUE,
      big.mark = " "
    )
}
```

**Základní období:** `r period`

**Výběr nehod:** `r accidents`

```{r, echo=FALSE, fig.align='center', fig.height=6}
if(nrow(params$data_accidents) > 0){

accidents_buffer <- 
  params$data_accidents %>%
  st_geometry() %>% 
  st_union() %>% 
  st_convex_hull()

if(as.double(st_area(accidents_buffer)) <= 10000000){

read_osm(
  accidents_buffer,
  ext = 1.1
) %>% 
  tm_shape() +
  tm_rgb() +
  # tm_shape(accidents_buffer) +
  # tm_polygons() +
  tm_shape(params$data_accidents) +
  tm_dots(
    size = 1,
    shape = 21,
    jitter = 0.1,
    alpha = 0.3,
    col = "red",
    border.col = "black",
    border.alpha = 1
  )
  
}else{
  print("Mapa se vykresluje pro výběry s plochou menší než 10 km2.")
}

}else{
  print("Ve výběru nejsou žádné nehody.")
}

```


**Přehled nehod:**

- Celkový počet dopravních nehod ve výběru: `r format_integer(nrow(params$data_accidents))`
- Počet obětí dopravních nehod: `r format_integer(died)`
- Počet těžce zraněných v dopravních nehodách: `r format_integer(swound)`
- Počet lehce zraněných v dopravních nehodách: `r format_integer(lwound)`

```{r, echo=FALSE}
if(died > 0){
params$data_accidents |>
      sf::st_drop_geometry() |> 
      dplyr::select(
        starts_with("casualties")
      ) |> 
      dplyr::summarise(
        across(
          everything(),
          sum
        )
      ) |> 
      tidyr::pivot_longer(
        everything()
      ) |>
      dplyr::filter(value > 0) |>
      dplyr::mutate(
        name = factor(
          name, 
          levels = names(casualties_nolinebreaks),
          labels = casualties_nolinebreaks
        ) |> as.character()
      ) |>
      dplyr::arrange(desc(value)) %>%
      dplyr::mutate(
        name = factor(name, levels = unique(name)),
        value = format(value, trim = TRUE, nsmall = 0, big.mark = " ")
      ) |>
    kable(
      col.names = c("Oběť","Počet"),
      align = "lr",
      caption = "Oběti dopravních nehod"
    )
}
```

```{r, echo=FALSE}
faults_nolinebreaks <- c(
  "1"="řidičem motorového vozidla",
  "2"="řidičem nemotorového vozidla",
  "3"="chodcem",
  "4"="lesní a domácí zvěří",
  "5"="jiným účastníkem silničního provozu",
  "6"="závadou komunikace",
  "7"="technickou závadou vozidla",
  "0"="jiné zavinení"
)

params$data_accidents |>
        sf::st_drop_geometry() |> 
        dplyr::group_by(accident_fault) |>
        dplyr::summarise(
          value = n(),
          .groups = "drop"
        ) |>
        dplyr::rename(name = accident_fault) |>
        dplyr::filter(value > 0) |>
        dplyr::mutate(
          name = factor(
            name, 
            levels = names(faults_nolinebreaks),
            labels = faults_nolinebreaks
          ) |> as.character()
        ) |>
        dplyr::arrange(desc(value)) %>%
        dplyr::mutate(
          name = factor(name, levels = unique(name)),
          value = format(value, trim = TRUE, nsmall = 0, big.mark = " ")
        ) |>
    kable(
      col.names = c("Nehody zaviněné","Počet"),
      align = "lr",
      caption = "Dopravní nehody podle zavinění"
    )
```

```{r, echo=FALSE}
causes_nolinebreaks <- c(
  "100" = "nezaviněná řidičem",
  "201" = "nepřizpůsobení rychlosti hustotě provozu",
  "202" = "nepřizpůsobení rychlosti viditelnosti",
  "203" = "nepřizpůsobení rychlosti vlastn. vozidla a nákladu",
  "204" = "nepřizpůsobení rychlosti stavu vozovky",
  "205" = "nepřizpůsobení rychlosti dopr.techn.stavu vozovky",
  "206" = "překročení předepsané rychlosti stanovené pravidly",
  "207" = "překročení rychlosti stanovené dopravní značkou",
  "208" = "nepřizpůsobení rychlosti bočnímu, nárazovému větru",
  "209" = "jiný druh nepřiměřené rychlosti",
  "301" = "předjíždění vpravo",
  "302" = "předjíždění bez dostatečného bočního odstupu",
  "303" = "předjíždění bez dostatečného rozhledu",
  "304" = "při předj. došlo k ohrož. protijedoucího řidiče v.",
  "305" = "při předj. došlo k ohrož. předjížděného řidiče v.",
  "306" = "předjíždění vlevo vozidla odbočujícího vlevo",
  "307" = "předj. v místech, kde je to zakazáno dopr.značkou",
  "308" = "při předj. byla přejeta podélná čára souvislá",
  "309" = "bránění v předjíždění",
  "310" = "přehlédnutí již předjíždějícího souběžně jed. voz.",
  "311" = "jiný druh nesprávného předjíždění",
  "401" = "jízda na červené světlo",
  "402" = "nedání předn. proti příkazu d.z. STŮJ DEJ PŘEDNOST",
  "403" = "nedání předn. proti příkazu d.z. DEJ PŘEDNOST",
  "404" = "nedání předn. vozidlu přijíždějícímu zprava",
  "405" = "nedání předn. při odbočování vlevo",
  "406" = "nedání předn. tramvaji, která odbočuje",
  "407" = "nedání předn. protijed.voz. při objíždění překážky",
  "408" = "nedání předn. při zařazování do proudu jedouc.voz.",
  "409" = "nedání předn. při vjížděnína silnici",
  "410" = "nedání předn. při otáčení nebo couvání",
  "411" = "nedání předn. při přejíždění z pruhu do pruhu",
  "412" = "nedání předn. chodci na vyznačeném přechodu",
  "413" = "nedání předn. při odboč.vlevo souběžně jedouc.voz.",
  "414" = "jiné nedání přednosti",
  "501" = "jízda po nespr.straně vozovky, vjetí do protisměru",
  "502" = "vyhýbání bez dostatečné boční vůle",
  "503" = "nedodržení bezpečné vzdálenosti za vozidlem",
  "504" = "nesprávné otáčení nebo couvání",
  "505" = "chyby při udání směru jízdy",
  "506" = "bezohledná, agresivní, neohleduplná jízda",
  "507" = "náhlé bezdůvodné snížení rychlosti jízdy,zastavení",
  "508" = "řidič se plně nevěnoval řízení vozidla",
  "509" = "samovolné rozjetí nezajištěného vozidla",
  "510" = "vjetí na nezpevněnou krajnici",
  "511" = "nezvládnutí řízení vozidla",
  "512" = "jízda (vjetí) jednosměrnou ulicí, silnicí",
  "516" = "jiný druh nesprávného způsobu jízdy",
  "601" = "závada řízení",
  "602" = "závada provozní brzdy",
  "603" = "neúčinná nebo nefungující parkovací brzda",
  "604" = "optřebení běhounu pláště pod stanovenou mez",
  "605" = "defekt pneumatiky - průrazem, náhlým únikem vzd.",
  "606" = "závada osvětlovací soustavy vozidla",
  "607" = "nepřipoj./poškoz. spoj. hadice pro brzd.přípoj.voz.",
  "608" = "nesprávné uložení nákladu",
  "609" = "upadnutí, ztráta kola vozidla (i rezervního)",
  "610" = "zablokování kol v důsledku mech. závady vozidla",
  "611" = "lom závěsu kola, pružiny",
  "612" = "nazajištěná, poškozená bočnice (i u přívěsu)",
  "613" = "závada závěsu pro přívěs",
  "614" = "utržená spojovací hřídel",
  "615" = "jiná technická závada"
)

params$data_accidents |>
        sf::st_drop_geometry() |>
        dplyr::select(
          accident_cause
        ) |>
        dplyr::group_by(
          accident_cause
        ) |>
        dplyr::summarise(
          value = dplyr::n()
        ) |>
        dplyr::slice_max(value, n = 10) |>
        dplyr::mutate(
          accident_cause = factor(accident_cause, 
                                  levels = names(causes_nolinebreaks),
                                  labels = causes_nolinebreaks
                                  ) |> as.character()
        ) |>
        dplyr::arrange(desc(value)) |>
        dplyr::mutate(
          accident_cause = factor(accident_cause, 
                                  levels = accident_cause),
          value = format(value, trim = TRUE, nsmall = 0, big.mark = " ")
        ) |>
        dplyr::rename(name = accident_cause) |>
    kable(
      col.names = c("Příčiny dopravních nehod","Počet"),
      align = "lr",
      caption = "Nejčastější příčiny dopravních nehod"
    )
```


```{r, echo=FALSE}
crashtype_nolinebreaks <- c(
  "1" = "srážka s jedoucím nekolejovým vozidlem",
  "2" = "srážka s vozidlem zaparkovaným, odstav.",
  "3" = "srážka s pevnou překážkou",
  "4" = "srážka s chodcem",
  "5" = "srážka s lesní zvěří",
  "6" = "srážka s domácím zvířetem",
  "7" = "srážka s vlakem",
  "8" = "srážka s tramvají",
  "9" = "havárie",
  "0" = "jiný druh nehody"
)

params$data_accidents |>
        sf::st_drop_geometry() |>
        dplyr::select(
          accident_type
        ) |>
        # dplyr::filter(
        #   accident_type != 0
        # ) |>
        dplyr::group_by(
          accident_type
        ) |>
        dplyr::summarise(
          value = dplyr::n()
        ) |>
        dplyr::slice_max(value, n = 5) |>
        dplyr::mutate(
          accident_type = factor(accident_type, 
                                  levels = names(crashtype_nolinebreaks),
                                  labels = crashtype_nolinebreaks
          ) |> as.character()
        ) |>
        dplyr::arrange(desc(value)) |>
        dplyr::mutate(
          accident_type = factor(accident_type, 
                                  levels = accident_type),
          value = format(value, trim = TRUE, nsmall = 0, big.mark = " ")
        ) |>
        dplyr::rename(name = accident_type) |>
    kable(
      col.names = c("Typ dopravní nehody","Počet"),
      align = "lr",
      caption = "Nejčastější typy dopravních nehod"
    )

```

```{r, echo=FALSE, fig.align='center', fig.height=3}
params$data_accidents |>
      sf::st_drop_geometry() |>
      tidyr::drop_na(driver_age) |>
      dplyr::mutate(
        agecat = cut(driver_age, breaks = c(0,5,9,14,17,20,24,34,44,54,64,Inf))
      ) |>
      dplyr::group_by(
        agecat,
        .drop = FALSE
      ) |> 
      dplyr::summarise(
        value = dplyr::n()
      ) |>
      ggplot(
        aes(y = value, x = agecat)
      ) +
      geom_col(
        fill = "#377eb8"
      ) +
      scale_x_discrete(
        "Věk řidiče"
      ) +
      scale_y_continuous(
        "Počet nehod"
      ) +
  labs(
    title = "Věk viníků dopravních nehod"
  ) +
      theme_classic(
        base_size = 10
      ) +
      theme(
        legend.position = "bottom",
        legend.title = element_blank(),
        axis.title.y = element_blank()
      )
```